openapi: 3.1.0
info:
  title: API сервер для проекта «Шесть городов»
  description: |-
    * Список ресурсов и маршрутов сервера «Шесть городов».
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
tags:
  - name: users
    description: Действия с пользователями
  - name: offers
    description: Действия с офферами
  - name: comments
    description: Действия с комментариями
paths:
  /users/register:
    post:
      tags:
        - users
      summary: Регистрация пользователя
      description: Регистрирует нового пользователя

      requestBody:
        description: Данные для создания нового пользователя
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createUser'
        required: true
      responses:
        "201":
          description: Пользователь зарегистрирован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        "409":
          description: Пользоватьель с таким email уже существует
  /users/login:
    post:
      tags:
        - users
      summary: Авторизация пользователя
      description: Авторизует пользователя по логину и паролю

    get:
      tags:
        - users
      summary: Проверка состояния пользователя
      description: Возвращает информацию по авторизованному пользователю
  /users/{userId}/avatar:
    post:
      tags:
        - users
      summary: Загрузка аватара для пользователя
      description: Загружает аватар пользователя по userId. Изображение должно быть в формате `png` или `jpg`

components:
  schemas:
    createUser:
      type: object

      properties:
        name:
          type: string
          example: Denis

        email:
          type: string
          example: test@yandex.ru

        password:
          type: string
          example: 123456

        avatar:
          type: string
          example: avatar.jpg

        userType:
          type: string
          example: standard
    user:
      type: object

      properties:
        id:
          type: string
          example: 6329c3d6a04ab1061c6425ea

        email:
          type: string
          example: test@yandex.ru

        avatar:
          type: string
          example: avatar.jpg


